## Data loading pipeline

In [56]:
import numpy as np

## Permutations 

In [59]:
x1 = np.array([[1, 2]])
x2 = np.array([[2, 3]])
x3 = np.array([[4, 5]])

y1 = np.array([0])
y2 = np.array([1])
y3 = np.array([1])

y_temp = [y1, y2, y3]
x_temp = [x1, x2, x3]
x = np.vstack(x_temp)
y = np.concatenate(y_temp)

x, y

(array([[1, 2],
        [2, 3],
        [4, 5]]),
 array([0, 1, 1]))

In [64]:
perm = np.random.permutation(len(x))
x_per = x[perm]
y_per = y[perm]

x_per, y_per

(array([[2, 3],
        [1, 2],
        [4, 5]]),
 array([1, 0, 1]))